app/models.py
from flask_sqlalchemy import SQLAlchemy
from map.map import advance_delivery, DELIVERED
from werkzeug.security import check_password_hash, generate_password_hash
from sqlalchemy.orm import relationship
from flask_login import UserMixin


db = SQLAlchemy()


class Package(db.Model):
    __tablename__ = "packages"

    id = db.Column(db.Integer, primary_key=True)
    name = db.Column(db.String(20), nullable=False)
    recipient = db.Column(db.String(20), nullable=False)
    origin = db.Column(db.String(20), nullable=False)
    destination = db.Column(db.String(20), nullable=False)
    location = db.Column(db.String(20), nullable=False)
    express_shipping = db.Column(db.Boolean)
    user_id = db.Column(db.ForeignKey("users.id"), nullable=False)

    user = relationship("User", back_populates="packages")

    @staticmethod
    def advance_all_locations():
        packages = Package.query.all()
        for package in packages:
            if package.location is not DELIVERED:
                package.location = advance_delivery(package.location,
                                                    package.destination)


class User(db.Model, UserMixin):
    __tablename__ = "users"

    id = db.Column(db.Integer, primary_key=True)
    user_name = db.Column(db.String(100), nullable=False, unique=True)
    email = db.Column(db.String(255), nullable=False, unique=True)
    hashed_password = db.Column(db.String(255), nullable=False)

    packages = relationship("Package", back_populates="user")

    @property
    def password(self):
        return self.hashed_password

    @password.setter
    def password(self, password):
        self.hashed_password = generate_password_hash(password)

    def check_password(self, password):
        return check_password_hash(self.password, password)

app/forms/login_form.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField
from wtforms.validators import DataRequired

class LoginForm(FlaskForm):
    credential = StringField("Username or Email", validators=[DataRequired()])
    password = PasswordField("Password", validators=[DataRequired()])
    submit = SubmitField("Login")

app/forms/shipping_form.py
from flask_wtf import FlaskForm
from wtforms import BooleanField, SelectField, StringField, SubmitField
from wtforms.validators import DataRequired
from map.map import map


def get_choices():
    locations = set()
    for location in map:
        locations.add(location)
        for location2 in map[location]:
            locations.add(location2)
    return list(locations)


choices = get_choices()


class ShippingForm(FlaskForm):

    sender_name = StringField("Sender Name", validators=[DataRequired()])
    recipient_name = StringField("Recipient Name", validators=[DataRequired()])
    origin = SelectField("Origin",
                         choices=choices,
                         validators=[DataRequired()])
    destination = SelectField("Destination", choices=choices,
                              validators=[DataRequired()])
    express_shipping = BooleanField("Express Shipping")
    submit = SubmitField("Submit")
    cancel = SubmitField("Cancel")

app/forms/signup_form.py
from flask_wtf import FlaskForm
from wtforms import EmailField, PasswordField, StringField, SubmitField
from wtforms.validators import DataRequired


class SignupForm(FlaskForm):
    user_name = StringField("Choose a username", validators=[DataRequired()])
    email = EmailField("Your email address", validators=[DataRequired()])
    password = PasswordField("Type a strong password", validators=[DataRequired()])
    submit = SubmitField("Signup")

app/__init__.py
from flask import Flask, redirect, render_template
from flask_migrate import Migrate
from flask_login import current_user, LoginManager, login_required
from .config import Configuration
from app.forms.shipping_form import ShippingForm
from app.routes.session import session_bp
from .models import db, Package, User


app = Flask(__name__)
app.config.from_object(Configuration)

app.register_blueprint(session_bp)


db.init_app(app)
migrate = Migrate(app, db)

login = LoginManager(app)
login.login_view = "session.login"

@login.user_loader
def load_user(id):
    return User.query.get(id)


@app.route("/")
@login_required
def index():
    rows = Package.query.filter(Package.user_id==current_user.id).all()
    user_info = {
        "name": current_user.user_name,
        "email": current_user.email
    }
    return render_template("package_status.html", rows=rows, user=user_info)


@app.route("/new_package", methods=["GET", "POST"])
@login_required
def add_new_package():
    form = ShippingForm()
    if form.validate_on_submit():
        data = form.data
        package_data = {"name": data["sender_name"],
                        "recipient": data["recipient_name"],
                        "destination": data["destination"],
                        "origin": data["origin"],
                        "location": data["origin"],
                        "express_shipping": data["express_shipping"]
                        }
        user = User.query.get(current_user.id)
        new_package = Package(**package_data, user=user)
        db.session.add(new_package)
        db.session.commit()

        Package.advance_all_locations()
        return redirect("/")

    return render_template("shipping_request.html", form=form)

@app.route("/package/delete/<int:id>")
@login_required
def delete_package(id):
    package_to_delete = Package.query.get(id)
    db.session.delete(package_to_delete)
    db.session.commit()
    return redirect("/")

app/routes/session.py
from flask import Blueprint, redirect, render_template, url_for
from flask_login import current_user, login_user, logout_user
from sqlalchemy import or_
from app.forms.login_form import LoginForm
from app.forms.signup_form import SignupForm
from ..models import db, User

session_bp = Blueprint("session", __name__, url_prefix="/session")


@session_bp.route("/login", methods=["GET", "POST"])
def login():
    if current_user.is_authenticated:
        return redirect('/')
    form = LoginForm()
    if form.validate_on_submit():
        print("submited the form")
        user_credential = form.credential.data
        user = User.query.filter(or_(User.user_name == user_credential,
                                 User.email == user_credential)).first()
        if not user or not user.check_password(form.password.data):
            form.login_error = "User not found or password didn't match"
            return render_template("login_form.html", form=form)

        login_user(user)
        return redirect("/")
    return render_template("login_form.html", form=form)


@session_bp.route("/logout", methods=["POST"])
def logout():
    logout_user()
    return redirect(url_for(".login"))


@session_bp.route("/signup", methods=["GET", "POST"])
def signup():
    form = SignupForm()
    if form.validate_on_submit():
        user_data = {
            "user_name": form.data["user_name"],
            "email": form.data["email"]
        }
        user = User(**user_data)
        user.password = form.data["password"]

        db.session.add(user)
        db.session.commit()

        return redirect(url_for(".login"))

    return render_template("signup_form.html", form=form)

app/templates/login_form.html
<!DOCTYPE html>

<html>
    <head>

    </head>
    <bod>
        <form method="POST" action="{{ url_for('session.login') }}">
            {{ form.csrf_token }}
            {% if form.login_error %}
                <div style="border: 2px solid red; background-color: rgb(143, 44, 44); border-radius: 5px; width: fit-content; padding: 4px;">
                    {{ form.login_error }}
                </div> <br>
            {% endif %}
            <div>
                {{ form.credential.label }}
                {{ form.credential() }}
            </div> <br>
            <div>
                {{ form.password.label }}
                {{ form.password() }}
            </div> <br>
            <div>
                {{ form.submit() }}
            </div>
        </form>
        <div>
            <p>Don't have an account? sign up <a href="{{ url_for('.signup') }}">HERE</a> </p>
        </div>
    </bod>
</html>

app/templates/package_status.html
<!DOCTYPE html>
<htm>
    <head>
        <link rel="stylesheet" href="{{ url_for('static', filename='styles/package_status.css') }}">
        <script src="{{ url_for('static', filename='scripts/profile_info.js') }}"></script>
    </head>
    <body>
        <div class="header">
            <nav>
                <ul>
                    <li style="list-style: none;"><a href="/">Home</a></li>
                    <li style="list-style: none;"><a href="/new_package">New package</a></li>
                </ul>
            </nav>
            <div class="profile">
              <img
                src="{{ url_for('static', filename='icons/user.png') }}"
              >
              <div class="user_info hidden">
                <p>{{ user.name }}</p>
                <p>{{ user.email }}</p>
                <form method="POST" action="{{ url_for('session.logout') }}">
                    <button type="submit">Logout</button>
                </form>
              </div>
            </div>
        </div>
        <table>
            <thead>
                <tr>
                    <th>id</th>
                    <th>sender</th>
                    <th>recipient</th>
                    <th>origin</th>
                    <th>destination</th>
                    <th>location</th>
                    <th>express shipping</th>
                    <th></th>
                </tr>
            </thead>
            <tbody>
                {% for row in rows %}
                 <tr>
                    <td>{{ row.id }}</td>
                    <td>{{ row.name }}</td>
                    <td>{{ row.recipient }}</td>
                    <td>{{ row.origin }}</td>
                    <td>{{ row.destination }}</td>
                    <td>{{ row.location }}</td>
                    <td>
                        {% if row.express_shipping %}
                         ✔
                        {% else %}
                         ❌
                        {% endif %}
                    </td>
                    <td>
                        <form
                          method="DELETE"
                          action="{{ url_for('.delete_package', id=row.id) }}"
                        >
                            <button type="submit">delete</button>
                        </form>
                    </td>
                 </tr>
                {% endfor %}
            </tbody>
        </table>
    </body>
</htm>

app/templates/shipping_request.html
<!DOCTYPE html>
<html>
    <head></head>
    <body>
        <form method="POST" action="{{ url_for('.add_new_package') }}">
           {{ form.csrf_token }}
           {% for field in form %}
            {% if field.type in ["SubmitField"] %}
              {{ field() }}
            {% elif field.type in ["BooleanField"] %}
              {{ field() }}
              {{ field.label }} <br> <br>
            {% elif field.type not in ["CSRFTokenField"] %}
              {{ field.label }}
              {{ field() }} <br> <br>
            {% endif %}
           {% endfor %}
        </form>
    </body>
</html>

app/templates/signup_form.html
<!DOCTYPE html>

<html>
    <head>

    </head>
    <body>
        <form Method="POST" action="{{ url_for('.signup') }}">
            {{ form.csrf_token }}
            <div>
                {{ form.user_name.label }} <br>
                {{ form.user_name() }}
            </div> <br>
            <div>
                {{ form.email.label }} <br>
                {{ form.email() }}
            </div> <br>
            <div>
                {{ form.password.label }} <br>
                {{ form.password() }}
            </div> <br>
            <div>{{ form.submit() }}</div>
        </form>
    </body>
</html>